// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleJob) DeepCopyInto(out *AnsibleJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleJob.
func (in *AnsibleJob) DeepCopy() *AnsibleJob {
	if in == nil {
		return nil
	}
	out := new(AnsibleJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnsibleJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleJobList) DeepCopyInto(out *AnsibleJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AnsibleJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleJobList.
func (in *AnsibleJobList) DeepCopy() *AnsibleJobList {
	if in == nil {
		return nil
	}
	out := new(AnsibleJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnsibleJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleJobResult) DeepCopyInto(out *AnsibleJobResult) {
	*out = *in
	in.Finished.DeepCopyInto(&out.Finished)
	in.Started.DeepCopyInto(&out.Started)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleJobResult.
func (in *AnsibleJobResult) DeepCopy() *AnsibleJobResult {
	if in == nil {
		return nil
	}
	out := new(AnsibleJobResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleJobSpec) DeepCopyInto(out *AnsibleJobSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleJobSpec.
func (in *AnsibleJobSpec) DeepCopy() *AnsibleJobSpec {
	if in == nil {
		return nil
	}
	out := new(AnsibleJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleJobStatus) DeepCopyInto(out *AnsibleJobStatus) {
	*out = *in
	in.AnsibleJobResult.DeepCopyInto(&out.AnsibleJobResult)
	in.Conditions.DeepCopyInto(&out.Conditions)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleJobStatus.
func (in *AnsibleJobStatus) DeepCopy() *AnsibleJobStatus {
	if in == nil {
		return nil
	}
	out := new(AnsibleJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleResult) DeepCopyInto(out *AnsibleResult) {
	*out = *in
	in.Completion.DeepCopyInto(&out.Completion)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleResult.
func (in *AnsibleResult) DeepCopy() *AnsibleResult {
	if in == nil {
		return nil
	}
	out := new(AnsibleResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Conditions) DeepCopyInto(out *Conditions) {
	*out = *in
	if in.AnsibleResults != nil {
		in, out := &in.AnsibleResults, &out.AnsibleResults
		*out = make([]AnsibleResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Conditions.
func (in *Conditions) DeepCopy() *Conditions {
	if in == nil {
		return nil
	}
	out := new(Conditions)
	in.DeepCopyInto(out)
	return out
}
